### ISSUE TITLE
The package 'gimp' could not be installed

### ISSUE THREAD

**Issue by faddeychen** [linuxmint/mintinstall#148]
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/AptClient/AptClient.py", line 74, in _run
    cache.commit(acquire_progress_monitor, install_progress_monitor)
  File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 519, in commit
    raise SystemError("installArchives() failed")
SystemError: installArchives() failed

**Comment by clefebvre** [comment]
There's not enough here to follow up. Also this shouldn't be happening anymore since we no longer use AptClient.
