### ISSUE TITLE
Mint instal

### ISSUE THREAD

**Issue by dusan2020** [linuxmint/mintinstall#208]
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 2106, in on_installer_task_ready
    config = configobj.ConfigObj(desktop_file)
  File "/usr/lib/python3/dist-packages/configobj.py", line 1229, in __init__
    self._load(infile, configspec)
  File "/usr/lib/python3/dist-packages/configobj.py", line 1318, in _load
    raise error
  File "<string>", line None
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 16.

**Comment by icarter09** [comment]
@dusan2020 can you provided any steps or more info on this issue? Thanks.
