### ISSUE TITLE
Software Manager does not install any applications in Debian Testing

### ISSUE THREAD

**Issue by amaroklinux** [linuxmint/mintinstall#342]
Hello, for a few days the app is not installing any application in Debian Testing.

From what I've seen, it could be some problem with Python 3.10.

There is an output that describes this.

```
AttributeError: 'NoneType' object has no attribute 'error_code'
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.AttributeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python3/dist-packages/defer/utils.py", line 62, in wrapper
    deferred = defer(function, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/defer/__init__.py", line 435, in defer
    assert isinstance(func, collections.Callable)
AttributeError: module 'collections' has no attribute 'Callable'
```

I hope there is a fix for this bug, even though Linux Mint still doesn't support Debian Testing, currently Bookworm.

Thank you in advance for your attention!

**Comment by mtwebster** [comment]
There's not nearly enough context there to trace it back to where this is occurring in mintinstall, and it's likely something we're using that's broken on testing.

Did it work then stop working? Or has it never worked on bookworm? Are you up-to-date on other packages?

**Comment by amaroklinux** [comment]
It never worked on Bookworm, and I think it's some problem related to Python 3.10, with the "collections" variant which from what I saw on the Python website, should change the variant to collections.abc Callable.  I don't understand programming, so I'm just assuming that's the problem.  As for the system, everything is updated day by day.  You could test Mint Install on Debian Testing and see what the problem is further and then detect the bug.
