### ISSUE TITLE
In Linux Mint 21.1 Vera, the Mintinstall Software Manager all of a sudden stopped working even though I changed absolutely no settings at all

### ISSUE THREAD

**Issue by ngalerchalegocity60330** [linuxmint/mintinstall#352]
UPDATE: After running the update manager and installing all the latest updates, the software manager ran again. It turns out that if you did not immediately update the operating system through the Update Manager, the software manager would not run. 

My experience in past Linux Mint versions was that that the software manager actually ran flawlessly even if the updates were not installed right away. I don't know if this is the exact problem or if it was something else. I'm not going to close this issue just yet so people can tell me what causes this exact problem.

When I put in the "mintinstall" program name on the terminal, this was what it outputted. I have absolutely no idea what this means...

```
MintInstall: Detected system architecture: 'x86_64'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 198, in _load_cache
    json_obj = JsonObject.from_json(json.load(f))
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 105979 column 32 (char 4073049)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 952, in do_activate
    if self.installer.init_sync():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 251, in init_sync
    self.cache = cache.PkgCache(self.pkg_type, self.cache_path, self.have_flatpak)
  File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 78, in __init__
    cache, sections, flatpak_remote_infos = self._load_cache()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 203, in _load_cache
    warn("Installer: Error loading pkginfo cache:", e)
  File "/usr/lib/python3/dist-packages/mintcommon/installer/misc.py", line 45, in warn
    argstr = " ".join(sanitized)
TypeError: sequence item 1: expected str instance, JSONDecodeError found
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_lib_linuxmint_mintinstall_mintinstall.py.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 198, in _load_cache
    json_obj = JsonObject.from_json(json.load(f))
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 105979 column 32 (char 4073049)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintinstall/mintinstall.py", line 952, in do_activate
    if self.installer.init_sync():
  File "/usr/lib/python3/dist-packages/mintcommon/installer/installer.py", line 251, in init_sync
    self.cache = cache.PkgCache(self.pkg_type, self.cache_path, self.have_flatpak)
  File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 78, in __init__
    cache, sections, flatpak_remote_infos = self._load_cache()
  File "/usr/lib/python3/dist-packages/mintcommon/installer/cache.py", line 203, in _load_cache
    warn("Installer: Error loading pkginfo cache:", e)
  File "/usr/lib/python3/dist-packages/mintcommon/installer/misc.py", line 45, in warn
    argstr = " ".join(sanitized)
TypeError: sequence item 1: expected str instance, JSONDecodeError found
```

**Comment by TheCubedMartian** [comment]
I have the exact same issue except I am on cinnamon, not vera. following.
